### ISSUE TITLE
ttree.iterate documentation bug

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/uproot4#102]
Noticed this: https://github.com/scikit-hep/uproot4/blob/21047924d1092a3bcd077774474edf1b5b4acaa8/uproot4/behaviors/TBranch.py#L1103-L1106

It appears that the documentation implies `report, events = ttree.iterate()` when it's actually `events, report = ttree.iterate()`.

**Comment by jpivarski** [comment]
Thanks! I just went in and fixed this as part of PR #101.
