### ISSUE TITLE
Simplify GHA conda

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/uproot4#12]
Miniconda is already installed in GHA. You may need https://github.com/scikit-hep/vector/blob/60d3637efc98ecf53665ea6e81198bc4d77827d8/.github/workflows/ci.yml#L57
but I don't think you need to depend on a custom action.

https://github.com/scikit-hep/uproot4/blob/4cd75f06218cf381e5906876e6b0b50b9dd9ca82/.github/workflows/build-test.yml#L21

**Comment by jpivarski** [comment]
That's great—I didn't know that and will take advantage of it soon.

**Comment by henryiii** [comment]
I learned about it from @chrisburr :)

**Comment by jpivarski** [comment]
Done in #18.
