### ISSUE TITLE
HTTP protocol doesn't follow redirect

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/uproot4#121]
I cannot open 
```python
uproot4.open("https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root")
```
yet I can open the place it `302` redirects to:
```python
uproot4.open("https://raw.githubusercontent.com/CoffeaTeam/coffea/master/tests/samples/nano_dy.root")
```

**Comment by jpivarski** [comment]
Adding my comment from Slack, for the record:

This is a missed case:

https://github.com/scikit-hep/uproot4/blob/d8a4b7203952bb7bd85cbf6d2ed481d610c83e67/uproot4/source/http.py#L163-L174

doesn't check for r`esponse.status == 302` (redirect) and use the connection to try again at `response.headers["location"]`.

Same for:

https://github.com/scikit-hep/uproot4/blob/d8a4b7203952bb7bd85cbf6d2ed481d610c83e67/uproot4/source/http.py#L244

which only returns True or False based on whether the status is 206 or not. This should be an issue asking to support redirects.

On the second issue of not being able to access the redirected file: I wasn't able to the first time, then I was every subsequent time. I verify that I can read the data in it. I don't know if this was a one-time GitHub thing or if it always needs to "warm up," or what.

**Comment by maxnoe** [comment]
When you are at it, please don't forget the other redirect status codes:

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_redirection
