### ISSUE TITLE
Doubly jagged int32_t arrays contain only 0s

### ISSUE THREAD

**Issue by tamasgal** [scikit-hep/uproot4#128]
Thanks to your awesome work in  https://github.com/scikit-hep/uproot4/pull/96 the reading of doubly jagged `float64` data is working well (the `f['E/Evt/trks/trks.fitinf']` of the example file). Today I spent more time on the the uproot4 migration of our I/O library and discovered that another doubly jagged branch of type `int32_t` is giving only zeros, however the `interpretation` is of course correct (well interpreted by both uproot3 and uproot4).

I know that you created a special case for both the `float64` and the `int32_t` cases, so I stepped through with the debugger, which brought me to https://github.com/scikit-hep/awkward-1.0/blob/e1fe6f2497ae007bdddcdbd60a08f7bbec4e1029/src/libawkward/io/uproot.cpp#L125 but now I am stuck since it seems OK to me. Anyways, I create this issue and meanwhile I also try to figure out why it's not working as expected.

Here is a session which `uproot3` just to show the reference values, which are perfectly fine:

```python
In [1]: from km3net_testdata import data_path

In [2]: import uproot as uproot3

In [3]: f = uproot3.open(data_path("offline/km3net_offline.root"))

In [4]: f['E/Evt/trks/trks.rec_stages'].show()
trks.rec_stages            TStreamerSTL               asgenobj(SimpleArray(STLVector(asdtype('>i4'))))

In [5]: f['E/Evt/trks/trks.rec_stages'].array()
/usr/local/lib/python3.8/site-packages/awkward/array/base.py:394: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return cls.numpy.array(value, copy=False)
Out[5]: <ObjectArray [[[1, 3, 5, 4], [1, 3, 5], [1, 3], [1, 3], [1, 3], ..., [1], [1], [1], [1]]] at 0x00011627b430>

In [6]: f['E/Evt/trks/trks.fitinf'].show()
trks.fitinf                TStreamerSTL               asgenobj(SimpleArray(STLVector(asdtype('>f8'))))

In [7]: f['E/Evt/trks/trks.fitinf'].array()
/usr/local/lib/python3.8/site-packages/awkward/array/base.py:394: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return cls.numpy.array(value, copy=False)
Out[7]: <ObjectArray [[[0.004957442219414389, 0.003417848024252858, ... , [], [], [], [], [], []]] at 0x00011627b0d0>
```

Now the readout with `uproot4`. As you can see the `fitinf` branch is read correctly, but the `rec_stages` give zeroes. The interpretation seems to be fine though:

```python
In [1]: import uproot4

In [2]: from km3net_testdata import data_path

In [3]: f = uproot4.open(data_path("offline/km3net_offline.root"))

In [4]: f['E/Evt/trks/trks.rec_stages'].show()
name                 | typename                 | interpretation
---------------------+--------------------------+-------------------------------
trks.rec_stages      | std::vector<int32_t>*    | AsObjects(AsArray(True, False,
In [5]: f['E/Evt/trks/trks.rec_stages'].interpretation
Out[5]: AsObjects(AsArray(True, False, AsVector(False, dtype('>i4'))))

In [6]: f['E/Evt/trks/trks.rec_stages'].array()
Out[6]: <Array [[[0, 0, 0, 0], [0, ... 0], [0], [0]]] type='10 * var * var * int32'>

In [7]: f['E/Evt/trks/trks.fitinf'].show()
name                 | typename                 | interpretation
---------------------+--------------------------+-------------------------------
trks.fitinf          | std::vector<double>*     | AsObjects(AsArray(True, False,
In [8]: f['E/Evt/trks/trks.fitinf'].interpretation
Out[8]: AsObjects(AsArray(True, False, AsVector(False, dtype('>f8'))))

In [9]: f['E/Evt/trks/trks.fitinf'].array()
Out[9]: <Array [[[0.00496, 0.00342, -295, ... [], []]] type='10 * var * var * float64'>
```

**Comment by jpivarski** [comment]
Since this has been implemented twice, once in Python and once in C++, maybe try to disable the C++ implementation to see if there's a difference? (Just for debugging, that is.) If it's the C++, the implementation is in here:

https://github.com/scikit-hep/awkward-1.0/blob/master/src/libawkward/io/uproot.cpp

You can step through that with `std::cout`, [compiling Awkward Array with localbuild.py](https://github.com/scikit-hep/awkward-1.0/blob/master/CONTRIBUTING.md#building-and-teseting-locally).

(This is why I want to get the deserialization 99% correct in Python first! Debugging in C++ is a pain!)

**Comment by jpivarski** [comment]
I fixed a bug in this part of the Awkward Array code in version 0.4.0. As part of a general clean-up, I noticed that it was emitting warnings on MacOS that pointed to a suspicious line. I fixed that and tried reading `trks.rec_stages`:

```python
>>> branch["trks.rec_stages"].array(entry_stop=10)
<Array [[[1, 2, 5, 3, 5, 4], ... 1], [1], [1]]] type='10 * var * var * int32'>
```

It won't be easy for me to check the "before": if you upgrade Awkward, does it work for you now?

**Comment by tamasgal** [comment]
Ah thanks, I had no time to look into that until now but I will have a look now!

**Comment by tamasgal** [comment]
Yes, I can confirm that it works now, thank you, as always :)
