### ISSUE TITLE
Make wiki publicly editable

### ISSUE THREAD

**Issue by tamasgal** [scikit-hep/uproot4#168]
Just a tiny note, you forgot to [make the wiki publicly editable](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/changing-access-permissions-for-wikis). I have a few tiny snippets which I would like to bring into shape in the next few days, nothing groundbreaking but maybe useful for the docs 😉

**Comment by jpivarski** [comment]
I had no idea! Okay, I think I fixed it. Thanks for pointing this out.

**Comment by tamasgal** [comment]
me neither and was scratching my head 🙈

Btw. I created a pull request towards the docs. Do you prefer the wiki?

**Comment by jpivarski** [comment]
Can you check to see that you can put it in the wiki?

Actually, I would rather it in the wiki, then I can control how to mix it into the documentation. Passing custom Interpretations wouldn't be one of the "basic" items.

**Comment by tamasgal** [comment]
Yes sure!

I just tried but I get the same error:

```
░ tamasgal@greybox.local:uproot4.wiki  master ⇡ uproot4_fork
░ 00:34:42 > git push
ERROR: Permission to scikit-hep/uproot4.wiki.git denied to tamasgal.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

░ tamasgal@greybox.local:uproot4.wiki  master ⇡ uproot4_fork
░ 00:34:45 128 > cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:scikit-hep/uproot4.wiki.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
	pushRemote = origin
```

**Comment by jpivarski** [comment]
If you're doing it from a git client, it might matter what URLs it had at the time that you cloned it. Can you just paste it into the web form? That's the simplest way to find out if you have permissions.

**Comment by tamasgal** [comment]
Yep, that works. I thought I tried both via HTTPS and SSH...

**Comment by jpivarski** [comment]
Okay, let's do that instead of #170, then. Thanks!

**Comment by tamasgal** [comment]
Yes, I closed the PR ;)
