### ISSUE TITLE
Support for RDataFrame RAdoptAllocator

### ISSUE THREAD

**Issue by donalrinho** [scikit-hep/uproot4#172]
The RDataFrame structure

vector<float,ROOT::Detail::VecOps::RAdoptAllocator<float> >

is stored in some ROOT files I am analysing. The class docs in ROOT are here:

https://root.cern/doc/master/classROOT_1_1VecOps_1_1RVec.html

It would be great if support could be added for this type.  

Thanks a lot!
Donal

**Comment by jpivarski** [comment]
Does this file have an example that I can use for testing?

https://github.com/donalrinho/uproot_fcc_edm4hep_test/blob/master/data/test.root

(This kind of fix has to be test-driven.) Thanks!

**Comment by donalrinho** [comment]
Hi Jim,

I'll prepare a test repo for you with a file!

Cheers,
Donal

**Comment by donalrinho** [comment]
Hi Jim,

Please find a test file and notebook here:

https://github.com/donalrinho/fcc_RAdoptAllocator_test

The ROOT file contains the same information stored both in `std::vector` format and the `RAdoptAllocator` format for comparison. `tree.show()` can read the `std::vector` branches, but not the `RAdoptAllocator` ones.

Cheers,
Donal

**Comment by jpivarski** [comment]
TIL `std::vector` can take more than one parameter:

```python
>>> import uproot4
>>> t = uproot4.open("issue-172.root:events")
>>> t["rec_part_px_VecOps"].member("fClassName")
<TString 'vector<float,ROOT::Detail::VecOps::RAdoptAllocator<float> >' at 0x7fa383f68510>
>>> t["rec_part_px_VecOps"].typename
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
...
ValueError: invalid C++ type name syntax at char 13

    vector<float,ROOT::Detail::VecOps::RAdoptAllocator<float> >
-----------------^
in file issue-172.root
```

But it [can take another argument](http://www.cplusplus.com/reference/vector/vector/): the allocator. First step is to add that to the type parsing (and perhaps all the rest of the STL containers should take an optional allocator as well).

**Comment by jpivarski** [comment]
This was the issue:

https://github.com/scikit-hep/uproot4/blob/08f7df2e09f581c57a96433caf33713332061750/tests/test_0172-allow-allocators-in-vector-typenames.py#L15

but it's resolved now (by ignoring the allocators; we don't need them for read-only access in Python). There weren't any other issues in the way, since everything was just a `std::vector<float>`.

**Comment by donalrinho** [comment]
Thanks for all the work here! Cheers, Donal
