### ISSUE TITLE
help() difficult to navigate

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/uproot4#190]
I can do `uproot4.open` for example, but when I do `help(uproot4)`, I won't find `open` listed there. I understand that `open` is implemented in a submodule, but `help` should list the function or class documentation on the level where that is available, because that's where people will look for it (I don't know exactly where `open` is implemented).

This works for iminuit., for example.

**Comment by jpivarski** [comment]
I was just about to address this, but `open` is the first thing listed under `help(uproot4)`. There's also a lot of introductory text in the [online documentation](https://uproot4.readthedocs.io/en/latest/basic.html); I think of docstrings as being more reference-oriented than tutorial-oriented.

```python
>>> help(uproot4)
```
```
Help on package uproot4:

NAME
    uproot4 - Uproot: ROOT I/O in pure Python and NumPy.

DESCRIPTION
    Nearly all of the functions needed for general use are imported here, but the
    documentation gives fully qualified names. For example, the most frequently
    used function in Uproot is
    
    .. code-block:: python
    
        uproot4.open("path/to/filename.root")
    
    but we refer to it in the documentation as :py:func:`~uproot4.reading.open`.
    
    Typical entry points for file-reading are
    
    * :py:func:`~uproot4.reading.open`
    * :py:func:`~uproot4.behaviors.TBranch.iterate`
    * :py:func:`~uproot4.behaviors.TBranch.concatenate`
    * :py:func:`~uproot4.behaviors.TBranch.lazy`
    
    though they would usually be accessed as ``uproot4.iterate``,
    ``uproot4.concatenate``, and ``uproot4.lazy``.
    
    The most useful classes are
    
    * :py:class:`~uproot4.behaviors.TBranch.HasBranches` (``TTree`` or ``TBranch``)
    * :py:class:`~uproot4.behaviors.TBranch.TBranch`
    * :py:class:`~uproot4.behaviors.TH1`
    * :py:class:`~uproot4.behaviors.TH2`
    * :py:class:`~uproot4.behaviors.TProfile`
    
    though they would usually be accessed through instances that have been read
    from files.
...
```

There are other documentation issues, and I'll be focusing on them next (ahead of the remaining feature requests).
