### ISSUE TITLE
Usability improvements in wrapper libs - change the attribute name mapping in array()

### ISSUE THREAD

**Issue by tamasgal** [scikit-hep/uproot4#192]
A little bit of background: our data contains a lot of nested structures and hard-to-remember branch paths, on top of that, there are classes with tons of attributes which are reused for different things, while a set of attributes are just noise, which we would like to hide from the users. For example there is a generic `Hit` class which is used for MC hits and also for DAQ hits, but only a subset of the attributes are valid in the MC context and another (partly overlapping subset) for the DAQ context.

I maintain a wrapper library for `uproot` which is tailored to our experiment and offers a few classes so that it's possible to do things like:

```python
r = WhateverReader("file.root")
r.events.hits.pmt_id   # returns a jagged array of PMT IDs for each event
r.events[2:5].hits.dom_id  # a jagged array of PMT IDs for a slice of events
r.events[:10].hits.dom_id[:5]  # a jagged array of the the first 5 DOM IDs of the first 10 events
```

Behind the scenes, `.events` maps to specific branch with a cryptic path and `.hits` to a subbranch, while `dom_id` and `pmt_id` etc. are also subbranches and `.lazyarray()` or `.array()` are called behind the scenes.
The indexing magic is done by propagating all the indices to the actual Jagged-array, so that these are equivalent:

```python
r.events[0].hits.pmt_id[:5] == r.events.hits[0].pmt_id[:5] == r.events.pmt_id[0][:5] # etc.
```

Such a call translates then to something like

```python
fobj["/a/long/cryptic/path/to/UglyPMT_ID_Naming"].lazyarray(interpretation, options)[0, :5]
```

For some branches I need to use custom interpretations and even some conversion to `awkward1` etc. But you get the idea, a lot of happening behind the scenes 😉 On top of that, there is tab completion which shows only meaningful attributes. To achieve all this, I introduced (mapper) configurations for each branch which can be passed to a generic class.

**Alright, sorry, long story short**, in `uproot4` everything is much easier since the Awkward1 arrays are working really nicely, so I can get rid of many optimisations and special hooks under the hood. But the basic problems remain and I think that many uproot users encounter these and create libraries around to make them more user-friendly, so I thought it would be useful to dump this somewhere, in case these are already solved in a much better way or if there is interest in providing a more general user API for these presumably repeated tasks when building upon uproot:

- inconvenient, hard-to-remember branch addresses
- "noise" in API (field naming, hiding unused fields etc.)
- grouping things which belong together but are stored in different branches
- indexing magic (see example above) which spans over multiple branches and propagates down to the data

Anyways, this issue is mostly about **renaming fields**, so let me come to the point 🙈 

Given an example file from our experiment, you can see some events which consist of a jagged array of hits. I took this example because it almost works and only needs some adjustments in the field names:

```python
>>> import uproot4

>>> from skhep_testdata import data_path

>>> f = uproot4.open(data_path("uproot-issue431b.root"))

>>> f["E/Evt/hits"].show()
name                 | typename                 | interpretation
---------------------+--------------------------+-------------------------------
hits                 | vector<Hit>              | AsGroup(<TBranchElement 'hits'hits.id              | int32_t[]                | AsJagged(AsDtype('>i4'))
hits.dom_id          | int32_t[]                | AsJagged(AsDtype('>i4'))
hits.channel_id      | uint32_t[]               | AsJagged(AsDtype('>u4'))
hits.tdc             | uint32_t[]               | AsJagged(AsDtype('>u4'))
hits.tot             | uint32_t[]               | AsJagged(AsDtype('>u4'))
hits.trig            | int32_t[]                | AsJagged(AsDtype('>i4'))
hits.pmt_id          | int32_t[]                | AsJagged(AsDtype('>i4'))
hits.t               | double[]                 | AsJagged(AsDtype('>f8'))
hits.a               | double[]                 | AsJagged(AsDtype('>f8'))
hits.pos.x           | double[]                 | AsJagged(AsDtype('>f8'))
hits.pos.y           | double[]                 | AsJagged(AsDtype('>f8'))
hits.pos.z           | double[]                 | AsJagged(AsDtype('>f8'))
hits.dir.x           | double[]                 | AsJagged(AsDtype('>f8'))
hits.dir.y           | double[]                 | AsJagged(AsDtype('>f8'))
hits.dir.z           | double[]                 | AsJagged(AsDtype('>f8'))
hits.pure_t          | double[]                 | AsJagged(AsDtype('>f8'))
hits.pure_a          | double[]                 | AsJagged(AsDtype('>f8'))
hits.type            | int32_t[]                | AsJagged(AsDtype('>i4'))
hits.origin          | int32_t[]                | AsJagged(AsDtype('>i4'))
hits.pattern_flags   | uint32_t[]               | AsJagged(AsDtype('>u4'))
```

In this case, `hits` is already accessible as an `awkward1.Array` but you can also read the branches separately. For this particular example however, only the following fields are of interest
`dom_id`, `channel_id`, `t`, `tot`, `trig`, everything else does not make sense in a specific context (due to the general `Hit` class which is unfortunately reused for everything, but this is what we have to live with).

Now in the first step I of course don't want to create (and allocate) a new array just to **rename** those fields, but directly modify the interpretation. We can also not change the binary structure of the dtype for obvious reasons. I tried something like this:

```python
>>> interpretation = AsGrouped(f["E/Evt/hits"], {'id': AsJagged(AsDtype('>i4')), 'dom_id': AsJagged(AsDtype('>i4')), 'channel_id': AsJagged(AsDtype('>u4')), 'tdc': AsJagged(AsDtype('>u4')),
...  'tot': AsJagged(AsDtype('>u4')), 'trig': AsJagged(AsDtype('>i4')), 'pmt_id': AsJagged(AsDtype('>i4')), 'time': AsJagged(AsDtype('>f8')), 'charge': AsJagged(AsDtype('>f8')), 'pos_x': As
... Jagged(AsDtype('>f8')), 'pos_y': AsJagged(AsDtype('>f8')), 'pos_z': AsJagged(AsDtype('>f8')), 'dir_x': AsJagged(AsDtype('>f8')), 'dir_y': AsJagged(AsDtype('>f8')), 'dir_z': AsJagged(AsD
... type('>f8')), 'pure_time': AsJagged(AsDtype('>f8')), 'pure_charge': AsJagged(AsDtype('>f8')), 'type': AsJagged(AsDtype('>i4')), 'origin': AsJagged(AsDtype('>i4')), 'pattern_flags': AsJa
... gged(AsDtype('>u4'))})
```

but this will fail since those field names are stored also deeper in the structure, in a keys-dictionary (the dtype names are coupled to the branch names):

```
KeyInFileError: not found: 'id'

    Available keys: 'hits.id', 'hits.tdc', 'hits.t', 'hits.a', 'hits.tot', 'hits.dir.x', 'hits.dir.y', 'hits.dir.z', 'hits.dom_id', 'hits.trig', 'hits.pmt_id', 'hits.type', 'hits.pos.x', 'hits.pos.y', 'hits.pos.z', 'hits.pure_t'...
```
I followed the stack trace and found myself in `HasBranches` where I came to the conclusion that it's not so trivial to hook into the attribute naming and remap those. I though I could introduce a `field_remap` dictionary (e.g. `{"hits.dom_id": "dom_id", `hits.t`: "time", ...}` etc.) somewhere, but it's not easy to see where it would fit the best to not mess around with low level mechanics and break other stuff (iterate, caching etc.), so clearly I need some advise from an expert (Jim 😉 ).

My next idea was to try to see what I can do on the `awkward1.Array` side since that feels more accessible and much safer, however, I could not figure out how to change field names after array initialisation. Maybe it's better to do this in uproot directly, no idea. In the end, it should also work with `iterate()` etc. where you already can select just a subset of the attributes, which is the way to hide the "noisy fields".

So maybe the most straightforward soulution is ff `iterate()` and `array()` would provide a `rename_fields` option, but as written above, I guess it will have to be propagated to quite a low level part of the code.

Sorry for the long issue, but I am sure you have some good ideas about how to deal with this and maybe I am not alone with these problems ;)

**Comment by jpivarski** [comment]
Two things that might be relevant for this: the `arrays`/`iterate`/etc. functions can take `aliases`. If the TTree has built-in `fAliases`, then these are used first, but you can also provide them as a user.

```python
>>> import uproot4
>>> import skhep_testdata
>>> t = uproot4.open(skhep_testdata.data_path("uproot-Zmumu.root"))["events"]
>>> t.arrays(["p1", "p2"])
Traceback (most recent call last):
...
KeyError: 'p1'
>>> t.arrays(["p1", "p2"], aliases={
...     "p1": "sqrt(px1**2 + py1**2 + pz1**2)",
...     "p2": "sqrt(px2**2 + py2**2 + pz2**2)"
... })
<Array [{p1: 82.2, p2: 60.6}, ... p2: 171}] type='2304 * {"p1": float64, "p2": f...'>
```

(There's no magic here: this is just applying the string-based formula as Python code after loading the necessary arrays, but if you build up a dict of aliases, you can hide a lot of formulae in a package.)

The second thing is [NanoEvents](https://coffeateam.github.io/coffea/api/coffea.nanoaod.NanoEvents.html): @nsmith- has been writing a wrapper like yours for CMS data, which renames and restructures the TTree without reading it (i.e. lazy reading). It was originally designed for ROOT files with a NanoAOD structure, but it has been generalized to be parameterized by a YAML file, such that two different ROOT file structures have successfully been read with it.

I doubt the NanoEvents infrastructure can apply custom Interpretations, but it might not be a huge extension.

For something like this, I'd rather build on top of Uproot than include it in Uproot, although there is this "rename_fields" like behavior through `aliases`, and ideally, Uproot should be coming up with the right Interpretations on its own, though I know you have some strange files.

**Comment by tamasgal** [comment]
It's a shame that I have not thought about using the alias functionality, thanks!
I will also look into NanoEvents, it sounds like I can borrow from there, very promising.

Given that the core functionality of renaming fields is there, I definitely agree that building upon instead of integrating it is the better choice.

**Comment by jpivarski** [comment]
> Jim linked to the awkward0 version of NanoEvents.

Yikes! I changed the link above to the new NanoEvents so that no one clicks through by mistake.

**Comment by tamasgal** [comment]
Alright, many thanks for both of you, I think I a have all the tools and inspiration to move forward. 

I'll close the issue now.

**Comment by nsmith-** [comment]
@tamasgal any chance you can re-use NanoEvents for your case? Happy to collaborate on it.

**Comment by jpivarski** [comment]
I agree that generalizing NanoEvents across experiments would be a great thing. It provides something unique that should sit at a layer above Awkward Array and Uproot, but still not be tied to a specific experiment (or TTree format, which it's already broken free of).

**Comment by tamasgal** [comment]
Indeed, I think that's a good idea in general. I just need to understand how NanoEvents works and how it maps to our use-case. We already have lots of code based on the current API and if it's possible to replace the inner parts, that would of course be great.

Do you think that the nanoevents part of coffea could be extracted, so that we can minimise dependencies?

**Comment by nsmith-** [comment]
For sure in the long run I would like to (plus a name change...). In the mean time, I would imagine your existing dependencies mostly overlap https://github.com/CoffeaTeam/coffea/blob/master/setup.py#L58-L74 but if those look too onerous do let me know (and which ones! we could try to slim a bit)

**Comment by tamasgal** [comment]
Ah ok, yes that seems quite huge compared to our low level I/O https://git.km3net.de/km3py/km3io/-/blob/master/requirements/install.txt 😉 

The library is really just a thin wrapper, in the sense that for a specific type of ROOT file, we only define the mappings for a branch and subbranches using a `BranchMapper` class (https://git.km3net.de/km3py/km3io/-/blob/6f893c07beae7addacb6b2db62e4e37391b04653/km3io/rootio.py#L13)  seen in action here:  https://git.km3net.de/km3py/km3io/-/blob/6f893c07beae7addacb6b2db62e4e37391b04653/km3io/offline.py#L25
And after then initialse a subclass of `Branch` in our `*Reader` classes, like here https://git.km3net.de/km3py/km3io/-/blob/6f893c07beae7addacb6b2db62e4e37391b04653/km3io/offline.py#L205

That will then take over the mapping, tab-completion and index propagation as shown in the above example, by manipulating via `getattr`, `getitem`, `getkey` and alike, as you can see here https://git.km3net.de/km3py/km3io/-/blob/6f893c07beae7addacb6b2db62e4e37391b04653/km3io/rootio.py#L169
The indices are all collected and finally unfolded and passed to the actual branch, directly coming from uproot (vai `unfold_indices`: https://git.km3net.de/km3py/km3io/-/blob/6f893c07beae7addacb6b2db62e4e37391b04653/km3io/tools.py#L31)

This is basically what then provides the above mentioned API:

```python
r = WhateverReader("file.root")
r.events.hits.pmt_id   # returns a jagged array of PMT IDs for each event
r.events[2:5].hits.dom_id  # a jagged array of PMT IDs for a slice of events
r.events[:10].hits.dom_id[:5]  # a jagged array of the the first 5 DOM IDs of the first 10 events
```

So in principle, everything is fairly simple and you see a lot of traces for some hacks, like the forced conversion to awkward arrays from uproot3 for specific branches (https://git.km3net.de/km3py/km3io/-/blob/6f893c07beae7addacb6b2db62e4e37391b04653/km3io/rootio.py#L37) or other cache/lazy related optimisations. Many of them are obsolete when transitioning to uproot4.

If I understood correctly, in `nanoevents` the mapper thing is basically the `TreeMakerSchema` (https://github.com/CoffeaTeam/coffea/blob/a5583401173859878b52dea44b14ed6c613aea81/coffea/nanoevents/schemas.py#L297) and I also see some mappings in `NanoAODSchema`: https://github.com/CoffeaTeam/coffea/blob/a5583401173859878b52dea44b14ed6c613aea81/coffea/nanoevents/schemas.py#L132 which are very similar to those we need, I guess.
I am trying  to wrap my head around and find out how I could implement a scheme for our files.

Here is a type of a ROOT file which does not use custom interpretations, so this should be I think easy to map in `NanoEvents`. This is how the file looks like in uproot4 (I shortened the list of keys, for the sake of simplicity):

```python
>>> import uproot4
>>> from km3net_testdata import data_path
>>> f = uproot4.open(data_path("offline/km3net_offline.root"))
>>> f["E/Evt"].keys()
['AAObject',
 'AAObject/TObject',
 'AAObject/TObject/fUniqueID',
 'AAObject/TObject/fBits',
 'AAObject/usr_data',
 'AAObject/usr_data/usr_data.holder',
 'AAObject/usr_names',
 'id',
 'det_id',
 'mc_id',
 'run_id',
 'mc_run_id',
 'frame_index',
 'trigger_mask',
 'trigger_counter',
 'overlays',
 't',
 't/t.fSec',
 't/t.fNanoSec',
 'hits',
 'hits/hits.id',
 'hits/hits.dom_id',
 'hits/hits.channel_id',
 'hits/hits.tdc',
 'hits/hits.tot',
 'hits/hits.trig',
 'hits/hits.pmt_id',
 'hits/hits.t',
 'hits/hits.a',
 'hits/hits.pos.x',
 'hits/hits.pos.y',
 'hits/hits.pos.z',
 'hits/hits.dir.x',
 'hits/hits.dir.y',
 'hits/hits.dir.z',
 'hits/hits.pure_t',
 'hits/hits.pure_a',
 'hits/hits.type',
 'hits/hits.origin',
 'hits/hits.pattern_flags',
 'trks',
 'trks/trks.fUniqueID',
 'trks/trks.fBits',
 'trks/trks.usr_data',
 'trks/trks.usr_names',
 'trks/trks.id',
 'trks/trks.pos.x',
 'trks/trks.pos.y',
 'trks/trks.pos.z',
 'trks/trks.dir.x',
 'trks/trks.dir.y',
 'trks/trks.dir.z',
 'trks/trks.t',
 'trks/trks.E',
 'trks/trks.len',
 'trks/trks.lik',
 'trks/trks.mother_id',
 'trks/trks.fitinf',
 'trks/trks.hit_ids',
 'trks/trks.error_matrix',
 'w',
 'index',
 'flags']
```

So, the entry at `"E/Evt"` is our vector of events, which consist of `hits` and `trks` and other parameters. That is what we translate to `f.events` and `f.events.hits.dir_x` etc (which points to `f["E/Evt/hits/hits.dir.x"].lazyarray(options...)` etc.).

This allows to do the fancy indexing like mentioned above and other stuff like handy iteration:

```python
for event in f.events:
    calib_hits = calibrate(event.hits, calibration)
    ...
```

As you can see, it's all about grouping things together and offering a user-friendly interface (tab completion,  hiding noisy stuff etc.):

![Screenshot 2020-11-20 at 21 20 03](https://user-images.githubusercontent.com/1730350/99846340-7096d300-2b76-11eb-9eba-ae95d5a7733a.png)
![Screenshot 2020-11-20 at 21 20 11](https://user-images.githubusercontent.com/1730350/99846350-71c80000-2b76-11eb-8ecc-175f5f3668ea.png)
![Screenshot 2020-11-20 at 21 21 42](https://user-images.githubusercontent.com/1730350/99846353-71c80000-2b76-11eb-8b84-c931b4e8670b.png)

Do you think that's easy to do with `NanoEvents`?

**Comment by tamasgal** [comment]
I just realised, it's a flood of source code links, sorry for that 🙈 but maybe it's easier to communicate the needs and implementations.
