### ISSUE TITLE
OSError when opening over HTTPS

### ISSUE THREAD

**Issue by mayou36** [scikit-hep/uproot4#220]
Loading the following ROOT file (from the starterkit lessions) produces an OSError. Worked with uproot3 before.

## Example code

```
f = uproot.open('https://starterkit.web.cern.ch/starterkit/data/advanced-python-2019/RD_distribution.root')
tree = f['tree']
tree.arrays(library='pd')  # fails here
```

while it works with uproot3
```
f = uproot3.open('https://starterkit.web.cern.ch/starterkit/data/advanced-python-2019/RD_distribution.root',)
tree = f['tree']
tree.pandas.df()
```

raises: `OSError: unrecognized byte range in headers of HTTP multipart: '308-37016'
for URL https://starterkit.web.cern.ch/starterkit/data/advanced-python-2019/RD_distribution.root
`

**Comment by jpivarski** [comment]
The last branch, `"mu_pt_sum"`, has byte ranges like

```
[(308, 18671), (18671, 37017), (165181, 183507), (183507, 201850), (329993, 348355), (436552, 443498)]
```

but the HTTP server returned ranges

```
[(308, 37017), (165181, 201850), (329993, 348355), (436552, 443498)]
```

The first four were merged into two because they're contiguous. PR #221 adds a handler for that. Thanks for the report!

**Comment by mayou36** [comment]
Thanks a lot for taking care of it!
