### ISSUE TITLE
TH1 with variable binning: incorrect bin edges

### ISSUE THREAD

**Issue by kreisl** [scikit-hep/uproot4#222]
i am using uproot version 4. I have the bug since the latest update with `pip install uproot`

I do the following:
I would expect the two prints to give me the same result: [0., 1., 3.]
However edges() returns [0.,1.5, 3.].
It seems it ignores the variable binning.

```
import uproot
hist = uproot.open('test.root:hist')
print(hist.axis(0).edges())
print(hist.member("fXaxis").member("fXbins"))
```

I attached the root file as test.txt
[test.txt](https://github.com/scikit-hep/uproot4/files/5660279/test.txt)

**Comment by jpivarski** [comment]
There was an off-by-one error in the check for variable bins (8d6ef20cafd5e49a6786f4d8064a7afc0defdc09). Thanks!

```python
>>> import uproot
>>> h = uproot.open("uproot-issue-222.root:hist")
>>> h.axis().edges()
array([0., 1., 3.])
```
