### ISSUE TITLE
Can't turn ROOT tree to pandas df

### ISSUE THREAD

**Issue by GSarpis** [scikit-hep/uproot4#238]
Dear experts,

after updating uproot, I can no longer simply turn the opened tree to panda df and get a mysterious error.

MWE:
```
myfile = "input.root"
mytree = uproot.open(myfile)['DecayTree']
mydf = mytree.pandas.df()
```

Errror:

AttributeError: 'Model_TTree_v20' object has no attribute 'pandas'

Worked before, is this a know issue? 

Thank you,
Gedas

**Comment by jpivarski** [comment]
The reason for the Uproot 3 → Uproot 4 transition was to change the interface. Special functions for Pandas are not gone, but any function that produces an array (like `mytree.arrays`) can produce a Pandas DataFrame or Series if you pass `library="pd"` as an argument. See

https://uproot.readthedocs.io/en/latest/

for more details.

If you have a large script that would be difficult to transition to the new interface, you can install the `uproot3` package instead. This package is the last version with the old interface. Replacing

```python
import uproot
```

with

```python
import uproot3 as uproot
```

will give you all the old behavior, with a warning about the version not being supported anymore. (Hint: warnings can be [suppressed for one line of code](https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings) if you don't want to see this message.)

**Comment by GSarpis** [comment]
Thanks for a quick reply
