### ISSUE TITLE
Unexpected Results with uproot.concatenate

### ISSUE THREAD

**Issue by wctaylor** [scikit-hep/uproot4#248]
I am seeing some unexpected behavior when using uproot.concatenate. I am looking at waveform event data where each event has a single associated timestamp and then multiple features associated with the variable number of pulses possible within an event. So on a per-event basis, timestamp is zero dimensional (just a number), whereas the pulse quantities are 1D.

Concatenating multiple files and just selecting the timestamp data seems to work as expected - I get a 1D array of timestamps where the length of the array is the total number of events contained across all the files. 

However, if I include an additional branch to load, the behavior changes. Instead of a 1D array of timestamps, I get a 2D array. If file 1 contains N events, and file 2 contains M events, the timestamp array is as such

```
[ Row 1:   [file1_timestamp1, file1_timestamp2, ..., file1_timestampN],
  Row 2:   [file1_timestamp1, file1_timestamp2, ..., file1_timestampN],
  ...
  Row N:   [file1_timestamp1, file1_timestamp2, ..., file1_timestampN],
  Row N+1: [file2_timestamp1, file2_timestamp2, ..., file2_timestampM],
  Row N+2: [file2_timestamp1, file2_timestamp2, ..., file2_timestampM],
  ...
  Row N+M: [file2_timestamp1, file2_timestamp2, ..., file2_timestampM]]
```

Code

```
# This works as expected
data1 = uproot.concatenate("/path/to/rootfiles/*:events", "timestamp")
data1.timestamp # a 1D array of timestamps for all events, as desired

# This produces the unexpected shape for timestamps as shown above. 
# pulse_area, however, seems to work as expected.
data2 = uproot.concatenate("/path/to/rootfiles/*:events", ["timestamp", "pulse_area"])
data2.timestamp # a 2D array with the structure shown above
data2.pulse_area # a 2D array of pulse info for each event, as expected
```

I unfortunately can't share the root files I am working with.

Is this actually the intended behavior/is it just a problem with something I am doing?

**Comment by jpivarski** [comment]
Is the behavior you see similar to #244? If so, that was a bug, fixed in PR #245.

If it is the same issue, then I'd better push a new release soon because multiple people are running into it!

**Comment by wctaylor** [comment]
Ah, yes, I suspect that is probably the same thing. Sorry for the duplicate report - I just searched "concatenate" to look for previous issues. 

I'll wait for the next release then!

**Comment by jpivarski** [comment]
In a few minutes, [4.0.2rc1](https://github.com/scikit-hep/uproot4/releases/tag/4.0.2rc1) will be available [on PyPI](https://pypi.org/project/uproot/#history). Then you'll be able to

```bash
pip install -U "uproot>=4.0.2rc1"
```

and try it out. Another test to see if #244 is the same thing would be to try using the `arrays` method, rather than `concatenate`.

**Comment by jpivarski** [comment]
> In a few minutes, [4.0.2rc1](https://github.com/scikit-hep/uproot4/releases/tag/4.0.2rc1) will be available [on PyPI](https://pypi.org/project/uproot/#history).

It's ready: https://pypi.org/project/uproot/4.0.2rc1/

**Comment by wctaylor** [comment]
Thanks! That did indeed fix the issue.
