### ISSUE TITLE
parsing a struct with 2D arrays

### ISSUE THREAD

**Issue by soltz** [scikit-hep/uproot4#252]
This is a continuation of https://stackoverflow.com/questions/62519766/parsing-a-struct-using-2d-arrays-using-uproot/62520558#62520558 

Jim, 

  Thanks, for the fix on StackExchange.  Here is a small root file along with the macro that generated it so that you can test the automated interpretation.

[2DinStruct.root.gz](https://github.com/scikit-hep/uproot/files/4827751/2DinStruct.root.gz)
[Test2DinStruct.C.gz](https://github.com/scikit-hep/uproot/files/4827753/Test2DinStruct.C.gz)

Ron

**Comment by mdpunch** [comment]
I guess I wasn't clear.  Thanks for taking it into account.

Two worries I would have on the routine as-is is that:

- I have only taken a handful of the root data types into account, so it might fail with other datatypes.
  - so, I have 4 of the data types (I guess the most common) from the list of 12 here: https://root.cern/manual/root_classes_data_types_and_global_variables/#machine-independent-data-types 
- I am assuming that root is giving everything as big-endian (which works for me on x86_64 machine to produce the root files, and for this uproot reading)
  - But, I suppose this is okay, "It also is stored in machine independent format (ASCII, IEEE floating point, Big Endian byte ordering)" from the root docs https://root.cern.ch/root/htmldoc/guides/users-guide/InputOutput.html

If anyone has to hand the list of the data type descriptors that root uses in the branch titles with their equivalent as a Python (numpy) dtype, that would be sufficient... and especially if this is already somewhere in the uproot codebase, it would be better to leverage that.

But I would be happy to do some reverse engineering on that, if needed.

**Comment by jpivarski** [comment]
Information about how to interpret a branch is scattered around, and some of it is only available in titles that have to be parsed as strings, such as the [parameters of Double32/Float16](https://github.com/scikit-hep/uproot4/blob/20d8575e941c32559c7b5e62b0ed5f92bc4927d0/uproot/interpretation/identify.py#L206-L214).

Everything in ROOT is big-endian—that, at least, is easy to state as an absolute rule for now. The new RTNtuple will be little-endian, but everything in the RNTuple class (apart from the [RNTuple "anchor"](https://github.com/scikit-hep/uproot4/blob/main/uproot/models/RNTuple.py), which is an entry point) is distinct from the rest of ROOT I/O.

Manually providing an Interpretation is certainly allowed. That was my initial, quick [answer on StackOverflow](https://stackoverflow.com/a/62520558/1623645). Sometimes, that's what I recommend when I can't figure out why someone's classes have internal headers or are missing internal headers, but it's plain from the serialized file whether those headers exist or not, and I give them an Interpretation they can plug in. [Automatically determining the Interpretation](https://github.com/scikit-hep/uproot4/blob/20d8575e941c32559c7b5e62b0ed5f92bc4927d0/uproot/interpretation/identify.py#L275-L291) is, of course, better, and I'll see if your code can be merged in to improve that.

**Comment by mdpunch** [comment]
Okay, thanks!

**Comment by jpivarski** [comment]
I can't believe I lost track of this again! So I did it right away; PR #280 adds the leaf dimension interpretation.
