### ISSUE TITLE
uproot.concatenate with allow_missing raises KeyInFileError on files with empty trees

### ISSUE THREAD

**Issue by wctaylor** [scikit-hep/uproot4#261]
I am not sure whether this is a bug or not, but perhaps the error message could be made slightly clearer if not.

I have a large collection of root files, some of which clearly had some issues with their creation during the processing stage. I am attempting to run

```
data = uproot.concatenate("/path/to/rootfiles/*:events", 'pulse_area', allow_missing=True)
```

but some files have an empty `events` tree. 

```
>>> data = uproot.open("/path/to/broken/file.root")
>>> data['events'].keys()
[]
```
These files raise a `KeyInFileError` and references the provided branch name (in the example, that is `pulse_area`) and halt the concatenation. I naively expected the `allow_missing` option to permit the case of empty trees and continue running, but perhaps that is not the goal.

I am using uproot 4.0.2. I have attached an example root file. To reproduce, simply run

```
data = uproot.concatenate("example_root.root:events", 'pulse_area', allow_missing=True)
```

[example_root.txt](https://github.com/scikit-hep/uproot4/files/5953904/example_root.txt)

**Comment by jpivarski** [comment]
The goal of `allow_missing` was to allow for files that don't have a TTree with the given name. This one has the TTree, but not the requested TBranches. That's a different case, but it does sound like "allow missing" should apply. I'll look at where it fails.
