### ISSUE TITLE
Installing from conda installs v3.13.0

### ISSUE THREAD

**Issue by naidoo88** [scikit-hep/uproot4#271]
Hello! 

Apologies in advance if I have posted this in the wrong location.

When executing:
`conda install -c conda-forge uproot`
it appears to install uproot3 (v3.13.0) with the dependency of awkward v0.15.0.

`conda install -c conda-forge uproot4` 
offers uproot4 v0.1.2, as opposed to the current tag 4.0.3 which shows on the conda forge website.

I had understood the "naming transition" to have taken place, so I wanted to ask if this was expected behaviour?  

Cheers,
Paul

**Comment by chrisburr** [comment]
Creating a new environment seems to work:

```bash
$ conda create --name test uproot
$ conda activate test
$ python -c 'import uproot; print(uproot.__version__)'
4.0.3
```

Conda is probably avoiding upgrading too many packages and uproot 3 is a valid solution to the install command. Have you tried `conda install -c conda-forge uproot=4`?

**Comment by jpivarski** [comment]
@naidoo88, respond here if @chrisburr's solution doesn't work for you. I'm closing this now, but I can reopen it if it's still an issue.

**Comment by naidoo88** [comment]
Apologies for the slow response! I got sucked down a whole other environment hell.
Specifying uproot=4 indeed worked.  Must be as @chrisburr  said.

Thank you for your help!
