### ISSUE TITLE
It's possible for an XRootD callback to be called with `response=None`. What does that mean?

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/uproot4#276]
This was reported in a cms-coffea-users email list:

> Since last week I've encountered the error below [1] in a couple of files from the UL17/18 datasets and I haven't been able to figure out what's causing it. This error occurs even when the only thing I'm doing is counting the number of events in a file. Has anyone else seen this type of error before?
> 
> Additional info about my setup:
> coffea version: 0.7
> processor: run_uproot_job
> executor: futures_executor with NanoAODSchema
> running on lxplus
> 
> Thanks,
> Joseph
> 
> 
> [1]  Traceback (most recent call last):
>   File "/cvmfs/sft.cern.ch/lcg/views/LCG_97python3/x86_64-centos7-gcc8-opt/lib/python3.7/site-packages/XRootD/client/utils.py", line 39, in __call__
>     self.callback(self.status, self.response, self.hostlist)
>   File "/afs/cern.ch/user/j/jdulemba/.local/lib/python3.7/site-packages/uproot/source/xrootd.py", line 220, in callback
>     for chunk in response.chunks:
> AttributeError: 'NoneType' object has no attribute 'chunks'

That would be this function here:

https://github.com/scikit-hep/uproot4/blob/fc32791d3cb420ed95ded64ce544a6ca1484f481/uproot/source/xrootd.py#L221-L225

But if the callback is called with `response=None`, what does that mean? If we catch this, can we do anything more meaningful than raising an error message? If so, what's the XRootD error that causes it?

@kpedro88 responded with

> This looks the same as https://github.com/CoffeaTeam/coffea/issues/377.
> 
> The simplest workaround for now is:
> import uproot4
> uproot4.open.defaults["xrootd_handler"] = uproot4.source.xrootd.MultithreadedXRootDSource
> 
> (This may be fixed in a newer version of uproot4, but I'm not sure of the status there.)

Following the Coffea issue, there are links to yet more, similar issues.

Any follow-up here would be appreciated.

**Comment by kpedro88** [comment]
In https://github.com/CoffeaTeam/coffea/issues/377, @nsmith- pointed to https://github.com/scikit-hep/uproot4/pull/243 as possibly relevant to this issue. I'm not sure if it actually eliminates the issue, though.

**Comment by ryuwd** [comment]
When I ran into #253, `response=None` was being passed to the callback. Something was definitely wrong (a traceback was being printed complaining about the `NoneType`), but I wasn't able to understand what the problem was until I modified the callback to print information from the `status` object.

**Comment by ryuwd** [comment]
> If so, what's the XRootD error that causes it?

It could be any error that may occur when requesting chunks in this block of code:
https://github.com/xrootd/xrootd/blob/ced6cdeccc889d3943e4d5e93d5ce24c2b88512f/src/XrdXrootd/XrdXrootdXeq.cc#L2426-L2581

In #253 the cause was uproot4 was asking for too many chunks per request 
https://github.com/xrootd/xrootd/blob/ced6cdeccc889d3943e4d5e93d5ce24c2b88512f/src/XrdXrootd/XrdXrootdXeq.cc#L2453-L2458
