### ISSUE TITLE
TBranch.array returns instance of JaggedArray if entry_start >= entry_stop

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/uproot4#303]
When trying to load an array of a branch, but specifying `entry_start` to be equal or larger than `entry_stop` on a branch that is jagged, the returned object will be a `JaggedArray` instead of an array from the library specified.

```python
import uproot
f = uproot.open("https://raw.githubusercontent.com/CoffeaTeam/coffea/master/tests/samples/nano_dy.root")
branch = f["Events"]["Jet_pt"]
array = branch.array(entry_start=1, entry_stop=1)
```
I would expect `array` to be of type `awkward.Array` but it has type `uproot.interpretation.jagged.JaggedArray`.

I came across this while trying to search for bugs popping up in my code when I have no entries selected.

Tested on uproot version 4.0.6

**Comment by jpivarski** [comment]
That's right: you should never see this `JaggedArray` class; it's used internally when collecting data, before converting it to the appropriate NumPy/Awkward/Pandas output. Fixed in PR #304.

Thanks for reporting it!
