### ISSUE TITLE
Make the fact that one can't write with uproot4 more obvious

### ISSUE THREAD

**Issue by hassec** [scikit-hep/uproot4#310]
If I look at the [uproot3](https://github.com/scikit-hep/uproot3), there is a big bold text telling everyone that it is deprecated in favor of `uproot4`, so I switched and then later found out that the functionality of "writing" isn't yet supported. 

I feel that this is a bit unfortunate, considering that the writing part is quite a substantial part of an `I/O` library. 
So to avoid confusion, IMHO the missing writing functionality deserves a similar large bold info instead of the small note half a page down in the readme.

**Comment by jpivarski** [comment]
In fact I'm scheduled to be working on the writing aspect in a few days (depending on whether I finish [Vector](https://github.com/scikit-hep/vector) on time): https://github.com/scikit-hep/uproot4/issues/25#issuecomment-802917934

**Comment by jpivarski** [comment]
This is done or moot now; see #321.
