### ISSUE TITLE
uproot.recreate can't be found in Uproot 4

### ISSUE THREAD

**Issue by bockjoo** [scikit-hep/uproot4#324]
Hi,
I have python 3.8.3 installed by an anaconda installation:
(base) [bockjoo@cms ~]$ which python
/opt/cms/services/anaconda3/bin/python
(base) [bockjoo@cms ~]$ python -V
Python 3.8.3
But I can not find the attribute recreate and some other attributes:

(base) [bockjoo@cms ~]$ python 
Python 3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uproot
>>> dir(uproot)
['AsArray', 'AsDouble32', 'AsDtype', 'AsDtypeInPlace', 'AsDynamic', 'AsFloat16', 'AsGrouped', 'AsJagged', 'AsMap', 'AsObjects', 'AsPointer', 'AsSTLBits', 'AsSet', 'AsStridedObjects', 'AsString', 'AsStrings', 'AsVector', 'Cursor', 'DeserializationError', 'HTTPSource', 'KeyInFileError', 'LRUArrayCache', 'LRUCache', 'LZ4', 'LZMA', 'MemmapSource', 'Model', 'MultithreadedFileSource', 'MultithreadedHTTPSource', 'MultithreadedXRootDSource', 'ObjectSource', 'ReadOnlyDirectory', 'ReadOnlyFile', 'STLMap', 'STLSet', 'STLVector', 'TBranch', 'TTree', 'ThreadPoolExecutor', 'TrivialExecutor', 'XRootDSource', 'ZLIB', 'ZSTD', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_util', 'absolute_import', 'behavior_of', 'behaviors', 'cache', 'class_named', 'classes', 'classname_decode', 'classname_encode', 'compression', 'concatenate', 'const', 'containers', 'default_library', 'deserialization', 'dynamic', 'exceptions', 'extras', 'has_class_named', 'interpretation', 'iterate', 'language', 'lazy', 'model', 'models', 'no_filter', 'open', 'reading', 'reset_classes', 'source', 'unknown_classes', 'uproot', 'version']
>>> quit()

Is there a way to fix this?
Thanks,
Bockjoo

**Comment by jpivarski** [comment]
From this listing, it's clear that you're using Uproot 4. If you're looking for `uproot.recreate`, the file-writing feature is currently being added to Uproot 4: see #321. (Your timing is almost perfect, actually.) Watch that discussion to keep informed about when file-writing is ready to test.

Beyond file-writing, you'll find [quite a few differences between Uproot 3 and 4](https://uproot.readthedocs.io/en/latest/uproot3-to-4.html). If you need something to work just like Uproot 3, you can install the package that is now named [uproot3](https://pypi.org/project/uproot3/):

```bash
pip install -U uproot3 uproot3-methods awkward0
```
