### ISSUE TITLE
Only read single element of array in each element of TBranch to container.

### ISSUE THREAD

**Issue by Goldie643** [scikit-hep/uproot4#356]
I'm fairly sure this isn't possible given the way TBranches are processed, but I figured I'd ask anyway as this is a big performance hit for me at the moment given our data structure. Sorry in advance if I don't explain what I mean clearly or if I've missed a solution in the docs.

For branches whose elements are arrays it seems it's currently impossible to select an individual element of that array at the ``arrays()`` level. 

As an example, for:
``vertex[4]     | float[4]                 | AsDtype("('>f4', (4,))")``

If I only want the 0th ``vertex`` value, I currently have to do something like:
```
[0] f["foo"].arrays("vertex[4]", library="pd")
       vertex[4][0]  vertex[4][1]  vertex[4][2]  vertex[4][3]
0       2168.348682    432.486840  -4035.777621   2454.722301
[1] f["foo"].arrays(["vertex[4]", library="pd")["vertex[4][0]"]
0       2168.348682
```

which of course doesn't skip the (relatively slow) process of reading the values in and putting them into the output container. I assume there's no way around this as the entire array has to be read in when reading the branch, I was just wondering if there is any internal change to speed this up (or if there's a quicker approach).

**Comment by Goldie643** [comment]
Thanks for replying. I think I didn't explain my issue well enough or maybe I'm misunderstanding your reply. My problem isn't about reading specific rows as fast as possible, my problem is reading the values of a column where the entries are arrays (horizontal vs. vertical problem). Back to the ``vertex`` example, what I want to do is:
```
[0] f["foo"].arrays("vertex[4][0]", library="pd")
0       2168.348682
1       2374.811102
    ....
99      2838.820183
100     1743.911113
```

But I can't select the ``0``th element of ``vertex`` without loading the entire array then sub-selecting in the resulting dataframe like:

``[0] f["foo"].arrays("vertex[4]", library="pd")["vertex[4][0]"]``

I assume in most people's ROOT files they have a more reasonable structure where there would be separate ``vx``, ``vy``, ``vz`` and ``vt`` so you could do something like:

``[0] f["foo"].arrays("vx", library="pd")["vertex[4][0]"]``

but unfortunately this is the structure I'm stuck with, I have multiple branches like this, including one with 200+ values from which I only need one. It's a big performance hit to load all 200+ values and then select the column I need.

**Comment by jpivarski** [comment]
Oh! I did misunderstand your problem. If you have a TBranch of 4-vectors, it _is_ necessary to read all 4 components to get one1component. In this data structure (a TBranch of 4-element arrays), the other 3 components are interleaved between these.

If (in C++), you made a `struct { float x; float y; float z; float t; }` and turned on splitting, the `x`, `y`, `z`, and `t` would get split into 4 distinct TBranches, which would show up independently in Uproot. But a `float[4]` does not get split at any split-level setting.

**Comment by jpivarski** [comment]
I keep trying to answer these too quickly—you clearly state that you can't change the structure.

If you want only the zeroth component of each, you can read the whole thing into an `array` and do

```python
array[:, 0]
```

to get an array of the zeroth component, if that's what you're asking. Maybe use `library="np"` or `library="ak"` to get an array (not DataFrame) with that slicing syntax and then wrap it as a Pandas Series/DataFrame.

**Comment by Goldie643** [comment]
No problem, sorry for the misunderstanding!

I hadn't thought to go via NumPy or Awkward before wrapping in a DF, I don't know how much of the slowdown is due to Pandas specifically but I'll give it a go.

**Comment by jpivarski** [comment]
If you have any other issues, let me know!
