### ISSUE TITLE
Problem zipping fields

### ISSUE THREAD

**Issue by qbuat** [scikit-hep/uproot4#368]
I’m encountering a strange behaviour with the zip functionality of awkward arrays.
It seems that one of the field I am trying to zip is causing a failure.
The following small test
```
import uproot
rfile = uproot.open('data/user.qbuat.Q_tests_pu.425200.Pythia8EvtGen_A14NNPDF23LO_Gammatautau_MassWeight_v1_output.root/user.qbuat.25693926._000001.output.root')
tree = rfile['CollectionTree']
fields_1 = [
    'TauTracksAuxDyn.trackPt',
    'TauTracksAuxDyn.trackEta',
]
fields_2 = [
    'TauTracksAuxDyn.trackPt',
    'TauTracksAuxDyn.trackEta',
    'TauTracksAuxDyn.IsPileupTrackQ',
]
arr_1 = tree.arrays(fields_1, how='zip')
print (arr_1.TauTracksAuxDyn.fields)
arr_2 = tree.arrays(fields_2, how='zip')
print (arr_2.TauTracksAuxDyn.fields)
```
returns:
```
['trackPt', 'trackEta']
['IsPileupTrackQ']
```
while the second printout should return the 3 fields
```
['trackPt', 'trackEta', 'IsPileupTrackQ']
```
I have looked at the root file directly but I cannot find anything suspicious with this branch. The root file is available on CERNBox: /eos/user/q/qbuat/uproot_debug/user.qbuat.25693926._000001.output.root and it is about 700MB.

Best,
Quentin

**Comment by qbuat** [comment]
The public link on CERNBox: https://cernbox.cern.ch/index.php/s/yme329A3Ts3jF7S

**Comment by qbuat** [comment]
Hi @jpivarski,

Thanks for investigating the problem and from the pointers! Indeed there could be rare cases where the variable IsPileupTrackQ is not filled. I will fix this in the code that made that root file. 

In any case, I guess it's not a bad idea to have this case handled by uproot if only to not confuse the user with a crash but instead with a different data structure.

Best,
Quentin

**Comment by jpivarski** [comment]
What it was doing before was definitely wrong behavior (a.k.a. "bug"). It might still be a bit mysterious why `IsPileupTrackQ` comes out in a different field from `trackPt` and `trackEta` if the user is still unaware that they sometimes have different lengths. One good thing about the array-oriented approach is that this tiny difference in cardinality, which could easily be overlooked in a for-loop analysis, is highly visible in the array-oriented approach. Maybe we need better error messages to explain why that's happening, but at least it doesn't go silently unnoticed.
