### ISSUE TITLE
Strange zipping behaviour

### ISSUE THREAD

**Issue by qbuat** [scikit-hep/uproot4#377]
Hello,

I am trying to open a root file with uproot in zip mode. I have a series of fields representing various type of particles.
When I try to create an awkward array with all the fields at once, it seems that uproot gets confused about two containers and create a 'jagged0' array. At first I thought it was the same problem with my input file as discovered by @jpivarski in #368, but after closer look it seems different.

When I break down my list of fields to load in sub lists and try to create an awkward array for each sub list, the zipping works just fine.

I've put the root file on cernbox: https://cernbox.cern.ch/index.php/s/ybpXh90vRp8q06Q
A gist to reproduce the issue is available here: https://gist.github.com/qbuat/8ac731f5cff4ceafc9faea129c89c094#file-uproot_debug-py. It is also attached to this issue as txt: [uproot_debug.txt](https://github.com/scikit-hep/uproot4/files/6633966/uproot_debug.txt)

Best,
Quentin

```python
$ python -i uproot_debug.py
/Users/quentin/bbtautau_mhh/data/group.phys-hdbs.mc16_13TeV.364128.HIGG4D3.e5307_s3126_r10201_p3978.bbtt_hh_v15-01_CxAOD.root/group.phys-hdbs.21763855._000003.CxAOD.root
['EventInfo___NominalAuxDyn.MCEventWeight', 'EventInfo___NominalAuxDyn.eventNumber', 'EventInfo___NominalAuxDyn.mcChannelNumber', 'jagged0', 'AntiKt4EMPFlowJets_BTagging201903___NominalAuxDyn', 'MET_Reference_AntiKt4EMPFlow___NominalAuxDyn']
['EventInfo___NominalAuxDyn.MCEventWeight', 'EventInfo___NominalAuxDyn.eventNumber', 'EventInfo___NominalAuxDyn.mcChannelNumber']
['TruthParticles___NominalAuxDyn']
['TauJets___NominalAuxDyn']
['AntiKt4EMPFlowJets_BTagging201903___NominalAuxDyn']
['MET_Reference_AntiKt4EMPFlow___NominalAuxDyn']
>>>
```

**Comment by jpivarski** [comment]
It's probably getting confused by the double underscores. The `how="zip"` parameter makes some assumptions about the naming convention of branches that are looser than NanoAOD's, but not infinitely loose. It has to know what to call the outer and inner fields.

It's intended as a quick convenience, so if you're able to construct what you want manually, that's a better option.

**Comment by qbuat** [comment]
It only gets confused for a handful of files in the entire dataset though.

**Comment by qbuat** [comment]
I think I'm starting to understand.. in the problematic file,  TruthParticles and Taus have the same number of entries for all events:

```

**Comment by jpivarski** [comment]
I think this is resolved, right? Uproot's zipping is determined by whether the arrays fit together or not, and your data have rare cases that don't fit together (maybe that's reason enough for me to remove the feature—it makes the data type depend on the data values, which is usually undesirable).

**Comment by qbuat** [comment]
Hi @jpivarski,

Yes I understood the source of the 'error'. I agree with you that there is no perfect solution. Ultimately the 'jagged0' array is not a bad outcome but one needs to be aware of that feature in the code to understand.

A possible improvement (but maybe it is already there and I missed it) would be to be able to retrieve the decision on what fields where zipped together (at least in verbose mode) and / or to be able to force uproot to zip as we intend it.

Best,
Quentin

**Comment by jpivarski** [comment]
To have a "verbose mode" and to be able to force it (somehow, by changing the numbers of items in lists) argues for this to not be a convenience option in the array-fetching function, but to make it a separate step, so that it can be more fully parameterized. Already, this step can be performed manually in Awkward Array, maybe the option in the array-fetching function should be deprecated with a link to a tutorial on how to do that.

For now, though, there isn't a bug in the feature, so I'll close this.
