### ISSUE TITLE
Allowing ```TBranch:: filter_name``` to process expressions or  ```TBranch:: expressions``` to process regex?

### ISSUE THREAD

**Issue by MoAly98** [scikit-hep/uproot4#423]
I am trying to develop code which will parse a series of branches and use uproot to read those branches. The branches could be passed as a regex pattern or as an exact name or as an expression. 

I am looking to combine all the requested branches into an array and passing them in one go to uproot.  The TBranch argument  ```filter_name``` fails to match the expressions and the expressions list fails to process regex patterns. Even if I group expressions together and filters together,  ```exoressions``` always overrides the ```filter_name``` argument. Is it possible to allow the ```filter_name``` argument to process an expression or for the ```expression```  argument to process regex patterns?

**Comment by MoAly98** [comment]
Hi @jpivarski 

Thanks a lot for your reply. I will like into your suggestions. I wasn't looking for anything particularly complicated -- the goal was simply allow a user to specify something like 
new_branch = Branch(expression = (branch1*branch2)/2)
regex_banch = Branch(filter=*pattern*)
 and in the back-end I would change ```pattern -> /pattern/i ``` to ensure it is explicitly defiend as a regex pattern and I had hoped i would be able to pass this expression for the new branch at the same time to ```uproot.iterate()``` for example so that i can read both branches requested by user. Anyways, thanks a lot for the very detailed and helpful answers :)

**Comment by jpivarski** [comment]
I think I kept this open to be informative, but we can do that with Discussions now, so I'll convert this Issue into a Discussion.
