### ISSUE TITLE
```filter_name``` with a list of negative-lookahead Regex commands

### ISSUE THREAD

**Issue by MoAly98** [scikit-hep/uproot4#445]
Hi,

I am not sure if this is a bug in ```uproot``` or a lack of understanding of how regex commands are combined in the backend. I am trying to select all branches of a file which do not contain the words "jets" or "leptons". To do this I pass to the ```filter_name``` argument of ```uproot.iterate()``` the following list with negative-lookahead patterns:
 ```['/^(?!.*jets.*).*$/i', '/^(?!.*leptons.*).*$/i']```

It seems like when I do this, ```uproot``` does not apply either filters at all. If I apply just one of the two filters, I get the correct behaviour. I also get the correct behaviour if I passboth filters as one regex pattern``` /^(?!.*(jets|leptons).*).*$/i```. However, having to do this latter combination of filters into just one is not favourable for my framework. Is it expected that uproot cannot handle the list of negative look-aheads?

**Comment by jpivarski** [comment]
Filters are combined by union: of a name passes either of these regexes, it passes. Does that fit with what you're saying?

**Comment by MoAly98** [comment]
Yes, so in case of two negative regexes, this translates to no filter applied at all.

**Comment by jpivarski** [comment]
Okay, so in that case, it's not an error, right? Joining the regexes is one good way of dealing with it; replacing the steering with a function that returns True or False is another (which lets you use `and` and `or`).

Of there's no bug, we can close this.

**Comment by MoAly98** [comment]
thanks a lot! Yes, I'm happy to close this. I think though that having support for a chain of negative filters could be useful !
