### ISSUE TITLE
uproot.recreate doesn't exist

### ISSUE THREAD

**Issue by shahidzk1** [scikit-hep/uproot4#459]
Hi, 
I am using uproot 4.0.4 and when I use the command uproot.recreate the following error appears:
""
module 'uproot' has no attribute 'recreate'

"

**Comment by jpivarski** [comment]
Uproot writing (`uproot.recreate`, `uproot.create`, and `uproot.update`) was introduced in version 4.1.0 (with an important bug-fix in 4.1.1). Upgrading is the only way to get it.

I hope you don't mind me closing this issue quickly, but the above ought to fix it.
