### ISSUE TITLE
Add warning/error or handle ROOT-incompatible variable/column names

### ISSUE THREAD

**Issue by meliache** [scikit-hep/uproot4#460]
In my pandas dataframe, I have columns/variable names with whitespace and parantheses, which I had heard ROOT does not support. Just out of curiosity, I tried writing it to a ROOT TTree with uproot 4.1.3 and it worked without warnings. With uproot I could read the file back in again and got the column names back in the correct form. So in this aspect it seemed to me more advanced than ROOT and this is why I didn't file it as a bug.

However, when opening the file in the TBrowser (ROOT 6.24), I couldn't see most leaves/variables. I have a replacement dictionary to make variable names ROOT-compatible, and when writing the resulting root-compatible dataframe to a ROOT file, I could see all branches in TBrowser again.

I would suggest to give at least a warning when writing data to ROOT with ROOT-incompatible keys/variablenames. At least if the resulting file will be unusuable from ROOT. 

Except you think that the TTrees are valid and them not being visible in TBrowser is an implementation issue of ROOT/TBrowser, then feel free to close this.

**Comment by jpivarski** [comment]
Do you know what characters ROOT doesn't support? (I'm assuming these are characters in the branch names.)

If it shows up in `TTree::Print` but not in the TBrowser, I'm inclined to take `TTree::Print` as the definition of "ROOT supports it." That's the low-level view of the data.

In fact, since this is a proposal to emit a warning when creating branch names, the real question is whether you can create TTrees with these names using ROOT (directly with `TTree::Branch`). If ROOT can make these TTrees, but can't render them in TBrowser, that's an inconsistency within ROOT.

**Comment by meliache** [comment]
Ok I can't reproduce it... I just wanted to modify the data-frame so I can share it here without worries, but when I created the new ROOT file the branch names showed up in ROOT/TBrowser without any issue :man_shrugging: 
![image](https://user-images.githubusercontent.com/5121824/136240619-9af99391-701f-4a25-a385-0158202f9ba5.png)

**Comment by jpivarski** [comment]
I'm confused about the fact that the DataFrame does not have any columns named `"x"` and `"y"`, but these are the branches that `TTree::Print` shows. Okay, maybe `TTree::Print` can only show branches that satisfy a particular naming convention, so it should show a _subset_ of the branches. `"x"` and `"y"` aren't in the set.

I was going to ask if there was a mistake in your tests (like, looking at the wrong file...), and the fact that you can now open them in TBrowser suggests that there was. No problem if it was; I do that kind of thing all the time.

In the end, is there an issue reading branches with weird names? If not, let's close the issue. Thanks!
