### ISSUE TITLE
Support for boost-histogram 0.10.0

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/uproot4#50]
In https://github.com/scikit-hep/boost-histogram/issues/410, @HDembinski requested that I add an underscore to `sum_of_weighted_deltas_squared`, and this has broken Uproot's `to_boost()` method on TProfiles.

Now when reading a TProfile, we get the error:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-10-d946cc02fe81> in <module>
----> 1 mplhep.histplot(rfile['hprof;1'].to_boost())

/usr/local/Caskroom/miniconda/base/envs/bh-talk/lib/python3.8/site-packages/uproot4/behaviors/TProfile.py in to_boost(self)
    178         view.sum_of_weights_squared
    179         view.value = values
--> 180         view.sum_of_weighted_deltas_squared
    181 
    182         raise NotImplementedError(repr(self))

AttributeError: 'WeightedMeanView' object has no attribute 'sum_of_weighted_deltas_squared'
```

**Comment by henryiii** [comment]
This doesn't even seem to be used as far as I can tell...

**Comment by jpivarski** [comment]
The reason this was left half-implemented was to get input on how to make a sum-of-weights histogram in Boost. The code that's there goes into the ROOT minutiae of how to produce exactly the right errors for all the TProfile error modes; now I just need to know how to populate the boost-histogram `view`.

There are four error modes for TProfile, only one of which is the error on the mean. (The others are error estimates on the individual points that the bin was filled with, under different assumptions.) The user's choice of error mode is part of ROOT's metadata for the TProfile. By default, the `to_numpy` function returns `(values, errors)` for the error mode given in the metadata (and it's also a parameter of the `to_numpy` method).

What should happen in `to_boost` and `to_hist`? Always pick the error on the mean? If so, perhaps it should be calculated using the `values_errors` method and then squared? ROOT's method of calculating errors, even the errors on the mean, is not simple.

**Comment by HDembinski** [comment]
@jpivarski We have two "profiles", one computes the mean (storage.Mean), the other computes the weighted mean (storage.WeightedMean). The latter requires more memory per cell and is a bit slower, but handles the uncertainty of weighted samples properly. A conversion from TProfile may require storage.WeightedMean to be lossless, but it depends on the values that the user has fed into the TProfile.

Regarding to your other question, Boost-Histogram always returns the value and the variance of that bin, so in case of a profile, it returns the variance of the samples in the bin, not the error on the mean.

**Comment by HDembinski** [comment]
Our method of calculating errors is also not simple. The formulas are not simple, when you implement them in a numerically stable way.

**Comment by jpivarski** [comment]
I meant we're going to have a hard time synchronizing them, such that we fill containers with values that mean the same thing, though they might be computed differently. I was hoping for a shortcut or something transparent.

Maybe this will help, though: the ROOT documentation on TProfiles presents a high-level notational view: https://root.cern.ch/doc/master/classTProfile.html. The part that I've figured out is how to turn the data from C++ members into what they call `GetBinContent(j)` and `GetBinError(j)` on this page, for all of the four error options (`""`, `"s"`, `"i"`, `"g"`). From what you wrote above, it sounds like `storage.WeightedMean` is `GetBinContent(j)` for the Boost mean and `GetBinError(j)**2` with option `"s"` for the Boost variances. I don't think ROOT's TProfile has an equivalent of an unweighted mean.

I see no evidence for an adjustment for degrees of freedom in ROOT's derivation (what would typically be `N - 1`), so I think we're safe in squaring the "spread" to get true variances. If Boost histograms have a function for deriving display error bars from variances, that can be a good closure test that we've interpreted it right.

(I've been calling it "ROOT's calculation" all over the place, but I distinctly remember it from the HBOOK documentation. There it is, on page 51 under `CALL HBPROF`: http://osksn2.hep.sci.osaka-u.ac.jp/~taku/doc/hbook.pdf)

**Comment by HDembinski** [comment]
The high-level notation seems useful. In Boost Histogram, I used the convention that variance really always means the variance in that bin. If you make a weighted histogram, it is at the variance of the weights. If you mean a profile, it is the variance of the samples.

**Comment by jpivarski** [comment]
I think this has been implemented and it's just a matter of getting the Uproot → boost-histogram interface right, if it's not right now. Anyway, this is marked as a duplicate.

**Comment by jpivarski** [comment]
All of these duplicates will all go into #167, where this interface will get figured out, once and for all.
