### ISSUE TITLE
Trouble with modern LorentzVector classes

### ISSUE THREAD

**Issue by aperloff** [scikit-hep/uproot4#51]
I have flat ntuples containing `std::vector` of:
1. `ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::DefaultCoordinateSystemTag>`
2. `ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::DefaultCoordinateSystemTag>`
3. `ROOT::Math::LorentzVector<ROOT::Math::PtEtaPhiE4D<double> >`

uproot4 seems to be choking badly on these classes. Can you please take a look and make sure that it is able to handle these? An example file can be found at /uscms_data/d2/aperloff/YOURWORKINGAREA/SUSY/slc7/CMSSW_10_2_21/src/TreeMaker/Production/test/SplitLevelTest/Summer16v3.TTJets_SingleLeptFromT_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_split99Lorentz_RA2AnalysisTree.root.

I tried exploring the file with:
```python
import uproot4
f = uproot4.open("/uscms_data/d2/aperloff/YOURWORKINGAREA/SUSY/slc7/CMSSW_10_2_21/src/TreeMaker/Production/test/SplitLevelTest/Summer16v3.TTJets_SingleLeptFromT_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_split99Lorentz_RA2AnalysisTree.root")
t = f["TreeMaker2/PreSelection"]
t.show()
```

Most of the branches look as expected, but the ROOT::Math::LorentzVector branches have:
```bash
Electrons            | std::vector<ROOT::Ma | AsObjects(AsVector(True, Unknown_R
```
I have turned the split level to 99, so I would expect these to be `AsJagged` and not `AsObjects`. Also, use the `Unknown_R` thing going to be a problem? Even worse, the whole thing crashes on `ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::DefaultCoordinateSystemTag>` with two errors:
1. `uproot4.interpretation.identify.NotNumerical`
2. `ValueError: invalid C++ type name syntax at char 68`

A full log has been attached.
[uproot4crash.log](https://github.com/scikit-hep/uproot4/files/4938146/uproot4crash.log)

**Comment by jpivarski** [comment]
Actually, I'd consider this a success: the error message pointed directly at the issue (too often, the errors were downstream of the real error in Uproot3). It was the C++ type parser:

```
ValueError: invalid C++ type name syntax at char 68

    vector<ROOT::Math::PositionVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::DefaultCoordinateSystemTag> >
------------------------------------------------------------------------^
in file uproot4-issue-51.root
```

and yeah, the parser wasn't handling commas (other than in `std::map`):

```diff
--- a/uproot4/interpretation/identify.py
+++ b/uproot4/interpretation/identify.py
@@ -629,6 +629,10 @@ def _parse_node(tokens, i, typename, file, quote, header, inner_header):
             i, keys = _parse_node(
                 tokens, i + 2, typename, file, quote, inner_header, inner_header
             )
+            while tokens[i].group(0) == ",":
+                i, keys = _parse_node(
+                    tokens, i + 1, typename, file, quote, inner_header, inner_header
+                )
             _parse_expect(">", tokens, i, typename, file)
             stop = tokens[i].span()[1]
```

(Why does Uproot4 have a type parser? Because the only reliable way to determine types in ROOT files is by parsing the type names. There are some integer tags in TStreamers, but they're not consistent: for instance, hadd can drop TStreamers. So if we're going to be interpreting types from strings, at least it should be a bone fide parser, with a tokenizer and parsing rules, like "if you're in the template arguments (opened with a `<` token), fully parse an item, then expect a `>` token OR a `,` token and then fully parse another...".)

We can now see the electrons:

```python
>>> t["Electrons"].show()
name                 | typename             | interpretation                    
---------------------+----------------------+-----------------------------------
Electrons            | std::vector<ROOT::Ma | AsObjects(AsVector(True, Unknown_R
Electrons.fCoordinat | double[]             | AsJagged(AsDtype('>f8'))          
Electrons.fCoordinat | double[]             | AsJagged(AsDtype('>f8'))          
Electrons.fCoordinat | double[]             | AsJagged(AsDtype('>f8'))          
Electrons.fCoordinat | double[]             | AsJagged(AsDtype('>f8'))          
```

and read their data through the subbranches:

```python
>>> t["Electrons.fCoordinates.fPt"].array()
<Array [[], [], [], [21.8, ... [], [], [56.5]] type='100 * var * float64'>
>>> t["Electrons.fCoordinates.fEta"].array()
<Array [[], [], [], ... [], [], [-0.605]] type='100 * var * float64'>
```

but I need to inhibit attempts to read from the `"Electrons"` branch, which doesn't really contain any data:

```python
>>> t["Electrons"].array()
uproot4.deserialization.DeserializationError: attempting to get bytes 0:6
outside expected range 0:4 for this Chunk
in file uproot4-issue-51.root
in object /TreeMaker2/PreSelection
```

The error message ought to be something like, "This is a structure branch; its data is contained in its subbranches" (listing them as a hint).

**Comment by aperloff** [comment]
Cool, glad you understand the issue. Can't wait to give it a try once you have a version with the improved type parser. And yes, a note not to access a "structure branch" will keep people like me from bugging you with non-errors ;)

@kpedro88, @nsmith-

**Comment by jpivarski** [comment]
On the roadmap is an idea for an attempted read of branches like `"Electrons"` as an [ak.zip](https://awkward-array.readthedocs.io/en/latest/_auto/ak.zip.html) of its four subbranches (issue #37).

**Comment by aperloff** [comment]
Oooo, I love that idea!
+1

**Comment by jpivarski** [comment]
When this passes and gets merged, you should be able to read this TreeMaker file. I read in branches with `filter_name="Elect*"` to see that it skipped the `AsGrouped` branch (just a stub/error message for now).
