### ISSUE TITLE
Add ability to break file connection in objects

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/uproot4#56]
And use this option in `__deepcopy__` and when handing objects to boost-histogram/hist. It should have the `file_path` and `uuid`, or at least for the latter set the `object_path` and `cache_key` in a permanent way.

@henryiii

**Comment by henryiii** [comment]
Do they also have a `__setstate__`/`__getstate__`? I would expect to be able to pickle a Histogram from ROOT, too.

**Comment by jpivarski** [comment]
I'm planning on it, though that would definitely break the connection to the original file.

**Comment by jpivarski** [comment]
Fixed in scikit-hep/uproot4#58; with a short list of exceptions (things like TDirectory, TTree, TBranch...), objects from a ROOT file are now detached from the original file. Thus, it wouldn't be possible to use these objects to read more data (which is why TDirectory, TTree, etc. are exceptions). But this means that the detached objects can be pickled and don't contain any transients, like locks or threads.

You can even save an object from a ROOT file into a pickle file and read it back in a new Python process, even though that object's class was derived from data in the ROOT file. (We pickle enough derived quantities from the TStreamerInfo to reconstitute the class object.)

**Comment by jpivarski** [comment]
This is done; somehow forgot to close it.
