### ISSUE TITLE
pandas FutureWarning: pandas.Int64Index is deprecated

### ISSUE THREAD

**Issue by VukanJ** [scikit-hep/uproot4#562]
Pandas 1.4.1 throws FutureWarnings when loading data into a pandas dataframe. This is not a critical bug but it will require your attention in the future.
```
python: 3.10
uproot: 4.20
pandas: 1.4.1
```
From an ipython session:
```
In [1]: import uproot

In [2]: import pandas

In [3]: pandas.__version__
Out[3]: '1.4.1'

In [4]: uproot.__version__
Out[4]: '4.2.0'

In [5]: uproot.open("file.root")["DecayTree"].arrays(library="pd")
/pathto/.local/anaconda3/envs/ftcalib/lib/python3.10/site-packages/uproot/interpretation/library.py:747: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  return (getattr(pandas, "RangeIndex", pandas.Int64Index), pandas.Int64Index)
```

**Comment by jpivarski** [comment]
As you can see from the code where the warning happens, we prefer `pandas.RangeIndex`, but accept `pandas.Int64Index` for some old versions of Pandas.

However,

```python
getattr(pandas, "RangeIndex", pandas.Int64Index)
```

does eagerly evaluate `pandas.Int64Index`, and that's a deprecation that will be an error in the future. (It makes you wish for a language in which function arguments can be specified as lazily evaluated: the `getattr` function isn't going to _need_ the default argument if `pandas.RangeIndex` exists.)

So I've reorganized this function in a way that should work in both new and old Pandas versions, and also removed our dependence on `distutils`, which is also deprecated in favor of `setuptools`.
