### ISSUE TITLE
TGAsymm errors("diff")

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/uproot4#587]
I suspect this is not behaving as intended
https://github.com/scikit-hep/uproot4/blob/main/src/uproot/behaviors/TGraphAsymmErrors.py#L35

Both low and high errors are given as positive numbers so instead of returning the "band", this returns their magnitude difference.

**Comment by jpivarski** [comment]
So are you saying that `diff` should be plus and `mean` should be minus?

Or that `low` and `high` should be redefined?

@kratsg was the original author (in #240). @kratsg, what do you think? Is this a correct interpretation?

**Comment by kratsg** [comment]
Well, I'm surprised anyone is using `diff`. I only needed it at the time for validation/xchecks, but it doesn't really have a lot of physical intuition. Both `high` and `low` errors are supposed to be positive as defined since they go in different directions.

**Comment by jpivarski** [comment]
Should it be removed? @andrzejnovak, what were you using it for?

In principle, all one needs is `high` and `low`, since the others can be derived from it. `mean` is useful because it turns a graph of asymmetric errors into a graph of symmetric errors. Does `mean` go in the right direction? (I would have thought that `mean` and `diff` should be opposites, whatever they are.)

**Comment by kratsg** [comment]
> Should it be removed? @andrzejnovak, what were you using it for?
> 
> In principle, all one needs is `high` and `low`, since the others can be derived from it. `mean` is useful because it turns a graph of asymmetric errors into a graph of symmetric errors. Does `mean` go in the right direction? (I would have thought that `mean` and `diff` should be opposites, whatever they are.)

They are meant to be opposites. I tried to balance it. One is "+" and one is "-". You could think of `diff` as a measure of the asymmetry.

**Comment by andrzejnovak** [comment]
I was using it to get "bin-width" though of course it can just be calculated from the separate err calls. Seems we can close it then, I was just expecting a different meaning behind the name.

**Comment by jpivarski** [comment]
Okay!
