### ISSUE TITLE
Uproot cannot read RVec

### ISSUE THREAD

**Issue by Tristan63170** [scikit-hep/uproot4#589]
I use uproot on SWAN (software stack 97a, uproot 4.0.0, awkward1 1.0.0) for one of my FCC analysis, and I have an issue. Since the new version of the FCCAnalyses stuff, the conversion of my data from ROOT tree to Awkward array is impossible. I checked the C++ function behind my quantities but nothing seems different comparing to the previous version (when everything was good).

With the .show() function I seen that the problem come from the fact that my old ROOT::VecObs::RVec<float or int> was seen like std::vector<float or int> by uproot where my new ROOT::VecObs::RVec<float or int> are seen like ROOT::VecOps::RVec<float or int>. Because of that uproot is not able to interpret these quantities (it gives AsObjects(UnknownROOT…)). I add that, by exploring my new and old .root with a TBrowser they seems identical.

I attach two files in this report, new is the .root with the issue and old is the previous version of it (without any issue), we can see a slight difference of size between the two files.

[new.txt](https://github.com/scikit-hep/uproot4/files/8632207/new.txt)
[old.txt](https://github.com/scikit-hep/uproot4/files/8632208/old.txt)

**Comment by jpivarski** [comment]
Using a recent Uproot, I got a different error (infinite recursion), but still something to be dealt with. Thanks for providing the files, especially since the before and after will help in reverse-engineering the `RVec` serialization.

**Comment by Tristan63170** [comment]
Yes I use a previous version of uproot with SWAN (it was the only configuration we have found to deal with our FCC stuff). In all case, say me if you manage to solve the issue and how. Thanks for your help.

**Comment by Tristan63170** [comment]
I don't know if it can be link or not to the uproot issue, but since this week I have an issue with root when I tried to explore the new .root file (everything run well with the old file) with a TBrowser (and it display an issue about TStreamer, RVec and std::vector), it can may be help. The root error is: 

Warning in <TStreamerInfo::Build>: Due to some major, backward-incompatible improvements planned for ROOT::RVec, direct I/O of ROOT::RVec objects will break between v6.24 and v6.26. Please use std::vectors instead. See the release notes of v6.24 for more information.
Warning in <TStreamerInfo::Build>: Due to some major, backward-incompatible improvements planned for ROOT::RVec, direct I/O of ROOT::RVec objects will break between v6.24 and v6.26. Please use std::vectors instead. See the release notes of v6.24 for more information.
Error in <TStreamerInfo::Build>: __gnu_cxx::__normal_iterator<const float*,vector<float,ROOT::Detail::VecOps::RAdoptAllocator<float> > >, discarding: const float* _M_current, no [dimension]

**Comment by jpivarski** [comment]
Whatever that is, it has nothing to do with this issue. (By the way, I'm working on it now.)

**Comment by jpivarski** [comment]
The serialization of `ROOT::VecOps::RVec` appears to be exactly the same as that of `std::vector`. But we don't trust the TStreamerInfo for `std::vector`, either, especially since we often override it to decode `std::vector<numeric_type>` more quickly with `AsJagged`, rather than `AsObjects`. So I added (in PR #593) exactly the same thing for `ROOT::VecOps::RVec`. If there is any difference between the two container types for type-combinations that I can't test because they aren't in your file, then we'll discover them down the road.

Thanks for the sample!

**Comment by Tristan63170** [comment]
I will pip upgrade my uproot and trying this, thanks !

**Comment by jpivarski** [comment]
It will be release 4.2.3. I'm waiting for #595 to get merged before deploying the new release.

**Comment by jpivarski** [comment]
It's ready: https://pypi.org/project/uproot/4.2.3/

Go ahead and `pip install -U uproot` now!
