### ISSUE TITLE
Delaying the opening of files in uproot.dask

### ISSUE THREAD

**Issue by kkothari2001** [scikit-hep/uproot4#602]
Just opening an issue to discuss feature 3 of the `uproot.dask()` as mentioned in #578 

> Sometimes, just opening files is an expensive operation that we want to avoid on the Dask client (e.g. there are too many files). We want to delay the tasks of opening the files and getting TTree objects out of them, so that this is only done on distributed workers, not locally on the user's client. This would have some drawbacks: you can only know the names and dtypes of the TBranches if you've read at least one TTree metadata (and assume they all have the same names and dtypes), and you can only know the lengths and chunk sizes of the arrays if you've read all TTree metadatas. It would be pretty hard to do much without knowing the TBranch names and dtypes, but [Dask allows arrays with unknown chunk sizes](https://docs.dask.org/en/stable/array-chunks.html#unknown-chunks). How would you add a open_files=False option that (a) reads TTree metadata only from the first file, (b) assumes all files have the same names and dtypes, and (c) creates Dask arrays with unknown chunks that open files upon compute? Unlike (2), this goes beyond what uproot.lazy could do.

I did give it a thought about how I could implement this. It looks like I'll have to wrap `uproot.open()` with a `dask.delayed()` decorator and then use `DelayedTTree[key].array()` as a delayed function call with `start` and  `stop` as parameters. This delayed array will then be fed to `dask.array.from_delayed` as already implemented.

As already discussed, unknown chunk sizes can be used here, but unknown chunk sizes seem to be an implicit paradigm in dask, with no clear way of passing info to `dask.array.from_delayed()` that we want to use unknown chunk sizes. Passing `(np.nan,)` or something like that might work. But I will have to test this.

Luckily, `dask.array.concatenate()` does have a `allow_unknown_chunksizes: bool` parameter that will be super useful in concatenating individual dask arrays. That means I will only have to figure out how to indicate unknown chunk sizes to `dask.array.from_delayed()`, and everything after that is straightforward.

**Comment by jpivarski** [comment]
Earlier today, I told @douglasdavis about your work, since you'll eventually be using https://github.com/ContinuumIO/dask-awkward/, and also we want to be sure you're using Dask effectively. He might have some ideas about making a Dask array from _N_ files without opening all _N_ files (opening just the first one to get the names and types). We necessarily would _not_ know how many entries each file has or what the total number of entries is.

**Comment by douglasdavis** [comment]
Thanks for pinging me here @jpivarski - yes it's certainly straightforward to delay opening files. The absolute simplest case would be something of the form:

```python
from dask.delayed import delayed
import dask.array as da

import uproot
from uproot.behaviors.TTree import TTree


@delayed
def delayed_tree(file_name: str, tree_name: str):
    return uproot.open(file_name)[tree_name]


@delayed
def delayed_array(tree: TTree, branch: str):
    return tree.arrays(branch, library="np", how=tuple)[0]


def arrays_from_uproot(files: list[str], tree: str, branches: list[str] | None = None):
    # use tree0 to get metadata; assume all other files have the same
    # structure.
    tree0 = uproot.open(files[0])[tree]

    # this is probably too simple; here just for example.
    if branches is None:
        branches = tree0.keys()

    # do something to determine the NumPy dtype for each branch (for
    # example we'll use a lambda function which can do this).
    get_dtype = lambda tree, branch: tree[branch].interpretation.numpy_dtype
    dtypes = {branch: get_dtype(tree0, branch) for branch in branches}

    # here `trees` is a list of Delayed objects that represent an
    # eventual concrete uproot TTree.
    trees = [delayed_tree(f, tree) for f in files]

    intermediate_results = {branch: [] for branch in branches}
    for branch in branches:
        for tree in trees:
            intermediate_results[branch].append(delayed_array(tree, branch))

    results = {}
    for branch, delayeds in intermediate_results.items():
        arrays = [
            da.from_delayed(d, shape=(np.nan,), dtype=dtypes[branch]) for d in delayeds
        ]
        results[branch] = da.concatenate(arrays, allow_unknown_chunksizes=True)

    return results
```
