### ISSUE TITLE
Incorrect units in memory size

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/uproot4#69]
In https://github.com/scikit-hep/uproot4/blob/7a03d3bc44ca76315c5f45de678b79ff8afc91ee/uproot4/_util.py#L242
the unit `kB`, `MB` are used for what appear to be `kiB`, `MiB`, etc.
See https://en.wikipedia.org/wiki/Binary_prefix

**Comment by jpivarski** [comment]
Thanks for the link—this always confuses me.
