### ISSUE TITLE
Error reading single and multi index branchs with pandas

### ISSUE THREAD

**Issue by badarot** [scikit-hep/uproot4#75]
Hi folks, I'm working with a TTree with two kinds of branches, a struct of doubles and single integers. And when a I try to load its data with pandas strange things happens.

The trees is like so.

    >>> tree.show()

    name                 | typename             | interpretation                    
    ---------------------+----------------------+-----------------------------------
    ionization           | struct {double x; do | AsDtype("[('x', '>f8'), ('y', '>f8
    electron             | struct {double x; do | AsDtype("[('x', '>f8'), ('y', '>f8
    ion                  | struct {double x; do | AsDtype("[('x', '>f8'), ('y', '>f8
    estatus              | int32_t              | AsDtype('>i4')                    
    istatus              | int32_t              | AsDtype('>i4')                    

When I load a single branch every thing works fine. I get a MultiIndex DataFrame for the struct and Single Index for the integer branch.
    
    >>> tree.arrays('ion', library='pd')

![issue1](https://user-images.githubusercontent.com/39627366/90965860-5cbdd100-e4a2-11ea-83a5-03c393e78a6b.png)

    >>> tree.arrays('istatus', library='pd')

![issue2](https://user-images.githubusercontent.com/39627366/90965864-63e4df00-e4a2-11ea-818d-454e071f3353.png)

But when I try to load those braches at the same time the index gets messed up and I end up with an empty DataFrame with a bunch of Nan subindexes.

    >>> tree.arrays(['ion', 'istatus'], library='pd')

![issue3](https://user-images.githubusercontent.com/39627366/90965868-6cd5b080-e4a2-11ea-81f0-c9a8140bfa29.png)

I don't know if this is a bug or I'm doing an illegal operation reading those two kinds of data at the same time. But when a do the same thing with `library='np'` every thing works fine.

**Comment by jpivarski** [comment]
To start, I reproduced the error by creating a similar file:

```c++
root [0] auto file = new TFile("issue-75.root", "RECREATE")
(TFile *) @0x7ffe052ea428
root [1] auto tree = new TTree("stuff", "")
(TTree *) @0x7ffe052ea428
root [2] struct stuff {double one; double two;}
root [3] stuff stuffy
(stuff &) @0x7f731d8d9018
root [4] int64_t stuffo
(long) 0
root [5] tree->Branch("stuffy", &stuffy, "one/D:two/D")
(TBranch *) 0x56180c6f9bc0
root [6] tree->Branch("stuffo", &stuffo, "stuffo/L")
(TBranch *) 0x56180c6f9400
root [7] stuffy.one = 1
(double) 1.0000000
root [8] stuffy.two = 2
(double) 2.0000000
root [9] stuffo = 3
(long) 3
root [10] tree->Fill()
(int) 24
root [11] stuffy.one = 1.1
(double) 1.1000000
root [12] stuffy.two = 2.2
(double) 2.2000000
root [13] stuffo = 33
(long) 33
root [14] tree->Fill()
(int) 24
root [15] stuffy.one = 1.2
(double) 1.2000000
root [16] stuffy.two = 2.3
(double) 2.3000000
root [17] stuffo = 333
(long) 333
root [18] tree->Fill()
(int) 24
root [19] tree->Write()
(int) 484
root [20] file->Close()
root [21] .q
```

And it looks like yours:

```python
>>> import uproot4
>>> f = uproot4.open("issue-75.root")
>>> f["stuff"].show()
name                 | typename             | interpretation                    
---------------------+----------------------+-----------------------------------
stuffy               | struct {double one;  | AsDtype("[('one', '>f8'), ('two', 
stuffo               | int64_t              | AsDtype('>i8')                    
>>> f["stuff"].arrays()
<Array [{stuffy: {one: 1, ... stuffo: 333}] type='3 * {"stuffy": {"one": float64...'>
>>> f["stuff"].arrays().tolist()
[{'stuffy': {'one': 1.0, 'two': 2.0}, 'stuffo': 3}, {'stuffy': {'one': 1.1, 'two': 2.2}, 'stuffo': 33}, {'stuffy': {'one': 1.2, 'two': 2.3}, 'stuffo': 333}]
```

and exhibits the error you're seeing:

```python
>>> f["stuff"].arrays(library="pd")
Empty DataFrame
Columns: [(stuffy, one, nan, nan, nan, nan), (stuffy, two, nan, nan, nan, nan), (s, t, u, f, f, o)]
Index: []
```

Now I can dig into it.

**Comment by jpivarski** [comment]
Pulling out individual branches is fine:

```bash
% python -c 'import uproot4; f = uproot4.open("issue-75.root"); print(f["stuff/stuffy"].array(library="pd"))'
   one  two
0  1.0  2.0
1  1.1  2.2
2  1.2  2.3
% python -c 'import uproot4; f = uproot4.open("issue-75.root"); print(f["stuff/stuffo"].array(library="pd"))'
0      3
1     33
2    333
dtype: int64
```

It's just the combination that goes haywire. That's in [Pandas.group](https://github.com/scikit-hep/uproot4/blob/3827f967da9c1031c8b5de14a877184d1089470d/uproot4/interpretation/library.py#L636), rather than [Pandas.finalize](https://github.com/scikit-hep/uproot4/blob/3827f967da9c1031c8b5de14a877184d1089470d/uproot4/interpretation/library.py#L509).

**Comment by jpivarski** [comment]
The problem was that some columns have multipart tuple structure (e.g. `("stuffy", "one")`) and others didn't (e.g. `"stuffo"`). Pandas's `MultiIndex.from_tuples` iterated through the letters of the string, assuming it to be a tuple (i.e. Pandas didn't check). So I added a step that explicitly puts all column names into tuples of the same length if any of them are tuples.

```python
% python -c 'import uproot4; f = uproot4.open("issue-75.root"); print(f["stuff"].arrays(library="pd"))'
  stuffy      stuffo
     one  two    NaN
0    1.0  2.0      3
1    1.1  2.2     33
2    1.2  2.3    333
```

**Comment by jpivarski** [comment]
And now I just realized that I committed that fix directly to master. I thought I was in a branch/PR! (Trying to work on too many things at the same time...)
